### ISSUE TITLE
Tenemos que poner asoc_members online

### ISSUE THREAD

**Issue by facundobatista** [PyAr/pyar_infra#13]
En prod seguro. También un staging?

`asoc_members` tiene un branch de develop, quizás tener staging con eso, master a prod?

Hay que importar la DB, también, y llevar las fotos (que son archivos separados).

Y hacer backup somehow...

**Comment by gilgamezh** [comment]
WIP: https://github.com/PyAr/pyar_infra/pull/16

**Comment by gilgamezh** [comment]
ya está up.
