### ISSUE TITLE
Staging Environment para Asoc Members

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyar_infra#38]
- [ ] Poner unas credenciales de Sentry
- [ ] Poner unas credenciales de la AFIP
- [ ] Poner unas credenciales de Mercadolibre
- [ ] Poner unas credenciales del servicio de mail
- [x] Poner unas credenciales de Azure
- [ ] Poner unas credenciales de Google Drive

**Comment by gilgamezh** [comment]
@tzulberti este ya lo podemos cerrar ¿no?

**Comment by tzulberti** [comment]
No, aunque tenemos deployado un entorno de staging, esos son servicios de 3ros que deberiamos configurar para staging.

**Comment by facundobatista** [comment]
Habría que probarlo, pero creo que AFIP tiene config "test" por default que serviría para staging...

Qué significa "credenciales de Azure"?

**Comment by tzulberti** [comment]
Perdon, me había olvidado de tildar esa opcion. Es el bucket de S3 donde se suben los archivos.

**Comment by gilgamezh** [comment]
Este esta para cerrar no? @facundobatista

**Comment by tzulberti** [comment]
@facundobatista se puede cerrar?

**Comment by facundobatista** [comment]
Sí, golazo, gracias.
