### ISSUE TITLE
mover archivo de lista de correos a k8s

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyar_infra#43]
Ahora que tenemos discourse deberiamos dejar estático para siempre el archivo de la lista y deployarlo en k8s. También sería bueno tenerlo disponible para que pueda bajarlo quien quiera.

**Comment by tzulberti** [comment]
Seria scrappear la pagina del archivo y ponerlo en un sitio statico? Si es asi, te puedo dar una mano con eso

**Comment by facundobatista** [comment]
Los archivos los tenemos, sería más bien servirlos de forma estática.

Digo, no hace falta screappear... a menos que sea más fácil scrappear que entender el formato del archivo :p

**Comment by tzulberti** [comment]
De donde me podria bajar el archivo? Asi hago pruebas con eso y voy viendo de generar las paginas estaticas

**Comment by facundobatista** [comment]
@tzulberti tenés ssh a `python.org.ar`?

**Comment by tzulberti** [comment]
Si, pero no se donde esta configurado el tema de la lista y no quiero empezar a buscar a lo bruto

**Comment by facundobatista** [comment]
Te lo dejé en `/tmp/pyar-archivo.tar.xz`, scp-teátelo a tu máquina local

**Comment by tzulberti** [comment]
Buenas. Subi el historico de la lista de correo en el Azure Storage:

https://listadecorreo.blob.core.windows.net/archive/index.html

Por ahi estaria bueno crear un DNS para eso, pero no tengo acceso a cloudfront para manejar ese tema.

pd: Tambien el archivo es mas o menos viejo (de mayo, por lo que me tendrian que pasar un nuevo archivo)

**Comment by facundobatista** [comment]
Yo puedo hacer un redirect. Algo como `archivo-lista.python.org.ar`?

Con respecto al archivo, te lo dejé en `/tmp/pyar-archivo-final.tar.xz`, en `python.org.ar`. El `shasum` me da `d77f68f8526dd7197d31eb3e283ef4b333aaffcb`.

**Comment by gilgamezh** [comment]
done by @tzulberti   Related to #62
