### ISSUE TITLE
Agregar HTTPs para la pagina web

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyar_infra#52]
La pagina web no esta usando HTTPs. Deberiamos de incluirlo para que sea mas seguro el tema

**Comment by facundobatista** [comment]
Vos decís que esto `https://www.python.org.ar/` funcione sin problemas, no? Creo que se le podría decir a cloudflare que lo maneje, confirmame que estamos hablando de lo mismo y le pego una mirada... gracias!

**Comment by facundobatista** [comment]
Mmm... veo que hiciste algo relacionado en #53 , pero eso es sólo para staging?

**Comment by tzulberti** [comment]
Actualmente para la asoc y eventol el HTTPs lo estamos manegando desde estos archivos.

Por el otro lado, lo hice solo para staging, porque no tengo entorno de prod para la web de PyAr porque nunca lo configure

**Comment by facundobatista** [comment]
Ah, ok, entonces manejalo vos por ese lado, por lo pronto te aprobé #53...

**Comment by gilgamezh** [comment]
https está habilitado desde que se migró hoy a k8s
