### ISSUE TITLE
Crear google analytics key

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyar_infra#54]
La idea es que alguien con acceso a la cuenta de PyAr de Google cree una clave de Google analytics para poder trackear la información de la web de PyAr (ticket relactionado de PyArWeb: https://github.com/PyAr/pyarweb/pull/468)

**Comment by facundobatista** [comment]
Cómo se saca una clave de google analytics?

Estoy intentando por [acá](https://developers.google.com/analytics?hl=en) y me da 503

**Comment by tzulberti** [comment]
Ya se creo esta clave y esta funcionando en producción
