### ISSUE TITLE
Crear un DNS o algo para el archivo de la lista de correo

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyar_infra#62]
El historial de la lista de correo esta en https://listadecorreo.blob.core.windows.net/archive/index.html

Estaria bueno tener un DNS un toque mejor que `blob.core.windows.net`

**Comment by gilgamezh** [comment]
lo configuré con  https://archivo.mailman.python.org.ar/. falta que funcione el SSL

**Comment by tzulberti** [comment]
Closed in #43
