### ISSUE TITLE
Que usamos para CI

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyar_infra#81]
Buenas. Para correr los tests, estamos usando difernetes cosas en diferentes proyectos:

- pyarbwe: travis
- asoc_members: travis
- wiki: Github Actions

Estaria bueno que todo esto este alineado y que siempre usemos lo mismo

**Comment by facundobatista** [comment]
La idea sería ir a GA. Me cansé de pelear con Travis :p (más detalles en [este comentario](https://github.com/PyAr/asoc_members/pull/207#issuecomment-846632860).

**Comment by facundobatista** [comment]
Estoy con este PR en asoc_members: https://github.com/PyAr/asoc_members/pull/209

**Comment by tzulberti** [comment]
Solucionado el tema de PyArWeb.
